# Generated by Django 3.0.2 on 2022-07-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='static/images/items'),
        ),
    ]
