# Generated by Django 3.0.2 on 2022-07-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150)),
                ('address', models.CharField(default='', max_length=200)),
                ('zipcode', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'billboard',
            },
        ),
    ]
